version: '3'

services:

  app:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5436:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./script/init/insert_tech.sql:/docker-entrypoint-initdb.d/insert_tech.sql
    env_file:
      - .env

volumes:
  postgres_volume: