INSERT INTO tech_solution (name, documentation_url, category, status, current_effectiveness) VALUES
                                                                                                 ('Java', 'https://docs.oracle.com/javase/8/docs/', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('Python', 'https://docs.python.org/3/', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('JavaScript', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('C++', 'https://isocpp.org/std/the-standard', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('C#', 'https://learn.microsoft.com/en-us/dotnet/csharp/', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('Ruby', 'https://www.ruby-lang.org/en/documentation/', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('Kotlin', 'https://kotlinlang.org/docs/home.html', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('PHP', 'https://www.php.net/docs.php', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('Swift', 'https://developer.apple.com/documentation/swift', 'LANGUAGES', 'NEW', 0),
                                                                                                 ('TypeScript', 'https://www.typescriptlang.org/docs/', 'LANGUAGES', 'NEW', 0),

                                                                                                 ('Docker', 'https://docs.docker.com/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Kubernetes', 'https://kubernetes.io/docs/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Git', 'https://git-scm.com/doc', 'TOOLS', 'NEW', 0),
                                                                                                 ('Jenkins', 'https://www.jenkins.io/doc/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Terraform', 'https://developer.hashicorp.com/terraform/docs', 'TOOLS', 'NEW', 0),
                                                                                                 ('Ansible', 'https://docs.ansible.com/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Maven', 'https://maven.apache.org/guides/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Gradle', 'https://docs.gradle.org/current/userguide/userguide.html', 'TOOLS', 'NEW', 0),
                                                                                                 ('Postman', 'https://learning.postman.com/docs/getting-started/introduction/', 'TOOLS', 'NEW', 0),
                                                                                                 ('ELK Stack', 'https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-elastic-stack.html', 'TOOLS', 'NEW', 0),

                                                                                                 ('Agile', 'https://agilemanifesto.org/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('Scrum', 'https://www.scrum.org/resources/scrum-guide', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('Kanban', 'https://kanbanize.com/kanban-resources/getting-started/what-is-kanban', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('TDD', 'https://www.agilealliance.org/glossary/tdd/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('CI/CD', 'https://docs.gitlab.com/ee/ci/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('BDD', 'https://cucumber.io/docs/bdd/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('Pair Programming', 'https://www.agilealliance.org/glossary/pairing/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('Code Review', 'https://smartbear.com/learn/code-review/what-is-code-review/', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('Refactoring', 'https://martinfowler.com/books/refactoring.html', 'TECHNIQUES', 'NEW', 0),
                                                                                                 ('DevOps', 'https://aws.amazon.com/devops/what-is-devops/', 'TECHNIQUES', 'NEW', 0),

                                                                                                 ('AWS', 'https://aws.amazon.com/documentation/', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Azure', 'https://docs.microsoft.com/en-us/azure/', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Google Cloud', 'https://cloud.google.com/docs', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Heroku', 'https://devcenter.heroku.com/categories/reference', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Salesforce', 'https://developer.salesforce.com/docs/', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Firebase', 'https://firebase.google.com/docs', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Oracle Cloud', 'https://docs.oracle.com/en/cloud/', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('IBM Cloud', 'https://cloud.ibm.com/docs', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('DigitalOcean', 'https://docs.digitalocean.com/', 'PLATFORMS', 'NEW', 0),
                                                                                                 ('Alibaba Cloud', 'https://www.alibabacloud.com/help', 'PLATFORMS', 'NEW', 0),

                                                                                                 ('Flutter', 'https://docs.flutter.dev/', 'TOOLS', 'NEW', 0),
                                                                                                 ('React', 'https://reactjs.org/docs/getting-started.html', 'TOOLS', 'NEW', 0),
                                                                                                 ('Vue.js', 'https://vuejs.org/v2/guide/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Angular', 'https://angular.io/docs', 'TOOLS', 'NEW', 0),
                                                                                                 ('Spring Boot', 'https://spring.io/projects/spring-boot', 'TOOLS', 'NEW', 0),
                                                                                                 ('Django', 'https://docs.djangoproject.com/en/stable/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Laravel', 'https://laravel.com/docs/8.x', 'TOOLS', 'NEW', 0),
                                                                                                 ('ASP.NET', 'https://dotnet.microsoft.com/en-us/learn/aspnet', 'TOOLS', 'NEW', 0),
                                                                                                 ('Selenium', 'https://www.selenium.dev/documentation/', 'TOOLS', 'NEW', 0),
                                                                                                 ('Unity', 'https://docs.unity3d.com/Manual/index.html', 'TOOLS', 'NEW', 0);
